[build.environment]
  # Keep in sync with CI in .github/workflows/node.js.yml
  NODE_VERSION = "24"

[[redirects]]
  from = "/details/*"
  to = "/BookReaderDemo/demo-internetarchive.html"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/BookReader/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
